import XCTest
@testable import GalaCore

final class CoreTests:XCTestCase {
    let now=ManilaDate.parse("2026-09-29")!
    func settings()->SearchSettings {var s=SearchSettings();s.firstDeparture="2026-10-05";s.lastDeparture="2026-10-10";s.adults=2;s.rooms=1;return s}
    func quote()->TripQuote {var q=TripQuote();q.id="trip";q.destination="CEB";q.departure="2026-10-05";q.returning="2026-10-07";q.adults=2;q.rooms=1;q.flight=500000;q.hotel=300000;q.activity=200000;q.transfers=80000;q.baggage=50000;q.mandatoryFeesIncluded=true;q.checkedAt=now;q.expiresAt=now.addingTimeInterval(3600);return q}
    func voucher()->Voucher {var v=Voucher();v.code="TESTONLY";v.provider = .hotel;v.percentage=true;v.value=1000;v.cap=50000;v.minSpend=100000;v.bookingStart="2026-09-01";v.bookingEnd="2026-09-30";v.travelStart="2026-10-01";v.travelEnd="2026-10-30";v.confirmed=true;v.eligibleQuoteIDs=["trip"];return v}
    func testThreeDaysMeansTwoNights(){XCTAssertEqual(quote().days,3);XCTAssertEqual(ManilaDate.add("2026-12-31",days:2),"2027-01-02");XCTAssertNil(ManilaDate.parse("2026-02-30"));XCTAssertEqual(ManilaDate.days("2028-02-28","2028-03-01"),2)}
    func testCompleteGroupArithmetic(){let r=Ranking.calculate([quote()],vouchers:[voucher()],settings:settings(),now:now)[0];XCTAssertEqual(r.food,210000);XCTAssertEqual(r.localTransport,60000);XCTAssertEqual(r.discount,30000);XCTAssertEqual(r.total,1370000);XCTAssertEqual(r.perPerson,685000)}
    func testVoucherCapAndMinimum(){var v=voucher();v.value=5000;XCTAssertEqual(v.saving(for:quote(),settings:settings(),now:now),50000);v.minSpend=400000;XCTAssertEqual(v.saving(for:quote(),settings:settings(),now:now),0)}
    func testOneBestVoucherPerProvider(){var a=voucher();a.code="SMALL";a.value=500;var b=voucher();b.code="BEST";b.value=2000;var c=voucher();c.provider = .flight;c.code="FLIGHT";c.percentage=false;c.value=10000;let r=Ranking.calculate([quote()],vouchers:[a,b,c],settings:settings(),now:now)[0];XCTAssertEqual(r.discount,60000);XCTAssertEqual(r.savings.count,2)}
    func testCannotDoubleCountIncludedDiscount(){var q=quote();q.includedVoucherCodes=["testonly"];XCTAssertEqual(voucher().saving(for:q,settings:settings(),now:now),0)}
    func testUnconfirmedAndDifferentQuotesHaveNoSaving(){var v=voucher();v.confirmed=false;XCTAssertEqual(v.saving(for:quote(),settings:settings(),now:now),0);v.confirmed=true;v.eligibleQuoteIDs=["other"];XCTAssertEqual(v.saving(for:quote(),settings:settings(),now:now),0)}
    func testChannelCardAndNewCustomer(){var v=voucher();v.channel="app";XCTAssertEqual(v.saving(for:quote(),settings:settings(),now:now),0);var s=settings();s.channel="app";v.payment="Specific card";XCTAssertEqual(v.saving(for:quote(),settings:s,now:now),0);s.payment="Specific card";v.newCustomerOnly=true;XCTAssertEqual(v.saving(for:quote(),settings:s,now:now),0);s.newCustomer=true;XCTAssertEqual(v.saving(for:quote(),settings:s,now:now),30000)}
    func testTravelAndBookingExpiry(){var v=voucher();v.travelEnd="2026-10-06";XCTAssertEqual(v.saving(for:quote(),settings:settings(),now:now),0);v=voucher();v.bookingEnd="2026-09-28";XCTAssertEqual(v.saving(for:quote(),settings:settings(),now:now),0)}
    func testExpiredQuotesExcludedAndCannotCarrySavings(){var q=quote();q.expiresAt=now.addingTimeInterval(-1);q.checkedAt=now.addingTimeInterval(-5000);XCTAssertTrue(Ranking.calculate([q],vouchers:[voucher()],settings:settings(),now:now).isEmpty);var s=settings();s.includeExpired=true;let r=Ranking.calculate([q],vouchers:[voucher()],settings:s,now:now);XCTAssertEqual(r.count,1);XCTAssertEqual(r[0].discount,0)}
    func testIncompleteQuoteCannotWin(){var q=quote();q.flight=0;XCTAssertTrue(Ranking.calculate([q],vouchers:[],settings:settings(),now:now).isEmpty);q=quote();q.mandatoryFeesIncluded=false;XCTAssertNotNil(q.validation);q=quote();q.origin="CRK";XCTAssertNotNil(q.validation);q=quote();q.returning="2026-10-13";XCTAssertNotNil(q.validation)}
    func testDemoDoesNotMixWithReal(){var q=quote();q.source = .demo;XCTAssertTrue(Ranking.calculate([q],vouchers:[],settings:settings(),now:now).isEmpty);XCTAssertEqual(Ranking.calculate([q],vouchers:[],settings:settings(),now:now,demo:true).count,1)}
    func testCheapestPerDestinationUsesWholeTrip(){var a=quote();a.id="a";a.flight=100000;a.hotel=900000;var b=quote();b.id="b";var c=quote();c.id="c";c.destination="ILO";c.flight=400000;let r=Ranking.cheapestPerDestination(Ranking.calculate([a,b,c],vouchers:[],settings:settings(),now:now));XCTAssertEqual(r.map(\.id),["c","b"])}
    func testPartySizeMustMatch(){var s=settings();s.adults=3;XCTAssertTrue(Ranking.calculate([quote()],vouchers:[],settings:s,now:now).isEmpty)}
    func testSearchEnumeratesEveryDateAndDestination(){let s=settings();XCTAssertEqual(s.dates().count,30);let jobs=ScanPlan.jobs(settings:s,destinations:Destination.all.map(\.code));XCTAssertEqual(jobs.count,30*65*3);XCTAssertEqual(Set(jobs.map(\.id)).count,jobs.count);XCTAssertEqual(Set(jobs.map(\.destination)).count,65)}
    func testInvalidSearchCannotExplodeWork(){var s=settings();s.minDays=9;XCTAssertEqual(s.dates().count,0);s=settings();s.lastDeparture="2035-01-01";XCTAssertEqual(s.dates().count,0)}
    func testRetryAfterRespected(){XCTAssertEqual(ScanPlan.retryDelay(attempt:2,retryAfter:"7200",now:now),7200);XCTAssertEqual(ScanPlan.retryDelay(attempt:2,retryAfter:"bad",now:now,jitter:0),60);XCTAssertGreaterThanOrEqual(ScanPlan.retryDelay(attempt:0,retryAfter:"-5",now:now),5)}
    func testMoneyParsingAndRounding(){XCTAssertEqual(Money.parse("1,234.56"),123456);XCTAssertNil(Money.parse("-1"));XCTAssertNil(Money.parse("123abc"));XCTAssertNil(Money.parse("1.999"));XCTAssertEqual(Money.parse("0"),0)}
    func testProviderHostValidation(){XCTAssertTrue(ProviderLinks.allowed(URL(string:"https://www.agoda.com/search")!));XCTAssertFalse(ProviderLinks.allowed(URL(string:"https://agoda.com.evil.test")!));XCTAssertFalse(ProviderLinks.allowed(URL(string:"http://www.klook.com")!));let u=ProviderLinks.url(.hotel,destination:"CEB",departure:"2026-10-05",returning:"2026-10-07",adults:2,rooms:1);XCTAssertTrue(u.absoluteString.contains("checkOut=2026-10-07"))}
    func testQuoteRoundTripJSON()throws{let e=JSONEncoder();e.dateEncodingStrategy = .iso8601;let d=JSONDecoder();d.dateDecodingStrategy = .iso8601;XCTAssertEqual(try d.decode(TripQuote.self,from:e.encode(quote())),quote())}
}
