import XCTest
@testable import GalaCore

final class PricingTests:XCTestCase {
    let now=ManilaDate.parse("2026-09-29")!
    func settings()->SearchSettings {var s=SearchSettings();s.firstDeparture="2026-10-05";s.lastDeparture=s.firstDeparture;s.minDays=3;s.maxDays=3;s.adults=2;s.rooms=1;return s}
    func candidate(_ provider:Provider,_ amount:Int,_ evidence:String,code:String="NRT",rooms:Int=1)->PriceCandidate {
        let job=ScanJob(provider:provider,destination:code,departure:"2026-10-05",returning:"2026-10-07",adults:2,rooms:rooms)
        return PriceCandidate(job:job,amount:amount,context:evidence,url:ProviderLinks.url(provider,destination:code,departure:job.departure,returning:job.returning,adults:2,rooms:rooms).absoluteString,capturedAt:now)
    }
    func inputs()->[PriceCandidate] {[
        candidate(.flight,120000,"Round trip PHP 1,200 per adult"),
        candidate(.hotel,100000,"PHP 1,000 per room per night"),
        candidate(.activity,60000,"PHP 600 per adult")
    ]}
    func testInternationalCoverageAndUniqueAirports(){XCTAssertEqual(Destination.international.count,27);XCTAssertEqual(Destination.domestic.count,38);XCTAssertEqual(Set(Destination.all.map(\.code)).count,65);XCTAssertTrue(Destination.international.allSatisfy(\.isInternational));XCTAssertFalse(Destination.all.contains{$0.code=="CRK" || $0.code=="MNL"});XCTAssertEqual(Set(Destination.international.map(\.code)),Set(["DPS","DMK","BKK","BWN","DAD","DXB","FUK","CAN","HAN","SGN","HKG","CGK","KHH","KUL","MFM","MEL","NGO","KIX","RUH","CTS","PVG","SYD","ICN","SIN","TPE","NRT","XMN"]))}
    func testInternationalHotelCountryAndFixedOrigin(){let hotel=ProviderLinks.url(.hotel,destination:"NRT",departure:"2026-10-05",returning:"2026-10-07",adults:2,rooms:1);let items=URLComponents(url:hotel,resolvingAgainstBaseURL:false)!.queryItems!;XCTAssertEqual(items.first{$0.name=="textToSearch"}?.value,"Tokyo, Japan");let flight=ProviderLinks.url(.flight,destination:"NRT",departure:"2026-10-05",returning:"2026-10-07",adults:2,rooms:1);let f=URLComponents(url:flight,resolvingAgainstBaseURL:false)!.queryItems!;XCTAssertEqual(f.first{$0.name=="o1"}?.value,"MNL");XCTAssertEqual(f.first{$0.name=="d2"}?.value,"MNL")}
    func testAutoWholePartyAndNightArithmetic(){let t=PriceCalculator.calculate(inputs(),vouchers:[],settings:settings(),now:now)[0];XCTAssertEqual(t.quote.flight,240000);XCTAssertEqual(t.quote.hotel,200000);XCTAssertEqual(t.quote.activity,120000);XCTAssertEqual(t.total,830000);XCTAssertEqual(t.perPerson,415000);XCTAssertFalse(t.quote.mandatoryFeesIncluded);XCTAssertNotNil(t.quote.validation)}
    func testRoomsAndFullStayAreNotMultipliedTwice(){let nightly=candidate(.hotel,100000,"PHP 1,000 per room per night",rooms:2);XCTAssertEqual(PriceCalculator.component(nightly)?.total,400000);let allRooms=candidate(.hotel,100000,"PHP 1,000 all rooms per night",rooms:2);XCTAssertEqual(PriceCalculator.component(allRooms)?.total,200000);let full=candidate(.hotel,400000,"Booking total PHP 4,000",rooms:2);XCTAssertEqual(PriceCalculator.component(full)?.total,400000)}
    func testTeasersRetailSavingsAndOneWayDoNotBecomeTripTotals(){for text in ["From PHP 1,000 per adult round trip","One way PHP 1,000 per adult","Round trip retail PHP 1,000 per adult","Round trip save PHP 1,000 per adult","Round trip PHP 1,000 child"]{XCTAssertNil(PriceCalculator.component(candidate(.flight,100000,text)),text)};XCTAssertNil(PriceCalculator.component(candidate(.hotel,100000,"PHP 1,000")))}
    func testMissingProviderRemainsIncomplete(){let t=PriceCalculator.calculate(Array(inputs().prefix(2)),vouchers:[],settings:settings(),now:now)[0];XCTAssertNil(t.total);XCTAssertEqual(t.missing,[.activity]);XCTAssertEqual(t.knownSubtotal,710000);var s=settings();var b=ExtraBudget();b.paidActivity=false;s.extras=b;let free=PriceCalculator.calculate(Array(inputs().prefix(2)),vouchers:[],settings:s,now:now)[0];XCTAssertEqual(free.total,710000)}
    func testExtrasArePartOfAutoTotal(){var s=settings();var b=ExtraBudget();b.transfers=10000;b.baggage=20000;b.other=30000;s.extras=b;let t=PriceCalculator.calculate(inputs(),vouchers:[],settings:s,now:now)[0];XCTAssertEqual(t.total,890000)}
    func testLowestCompleteGroupPriceWins(){var list=inputs();list.append(candidate(.hotel,210000,"Booking total PHP 2,100"));list.append(candidate(.hotel,50000,"Retail PHP 500 per room per night"));let t=PriceCalculator.calculate(list,vouchers:[],settings:settings(),now:now)[0];XCTAssertEqual(t.quote.hotel,200000);let archive=PriceCalculator.compact(list);XCTAssertEqual(archive.count,4)}
    func testWrongPartyExpiryAndPromoPagesExcluded(){var s=settings();s.adults=3;XCTAssertTrue(PriceCalculator.calculate(inputs(),vouchers:[],settings:s,now:now).isEmpty);XCTAssertTrue(PriceCalculator.calculate(inputs(),vouchers:[],settings:settings(),now:now.addingTimeInterval(3601)).isEmpty);let job=ScanJob(provider:.hotel,destination:"NRT",departure:"2026-10-05",returning:"2026-10-07",adults:2,rooms:1,overrideURL:"https://www.agoda.com/deals");let promo=PriceCandidate(job:job,amount:10000,context:"PHP 100 per room per night",url:"https://www.agoda.com/deals",capturedAt:now);XCTAssertTrue(PriceCalculator.calculate([promo],vouchers:[],settings:settings(),now:now).isEmpty)}
    func testActualCodeOnlyAfterExactCheckoutConfirmation(){let list=inputs();let s=settings();let first=PriceCalculator.calculate(list,vouchers:[],settings:s,now:now)[0];var v=Voucher();v.code="TESTONLY28%";v.provider = .activity;v.percentage=true;v.value=2800;v.bookingStart="2026-09-01";v.bookingEnd="2026-09-30";v.travelStart="2026-10-01";v.travelEnd="2026-10-31";v.eligibleQuoteIDs=[first.id];XCTAssertEqual(PriceCalculator.calculate(list,vouchers:[v],settings:s,now:now)[0].discount,0);v.confirmed=true;let discounted=PriceCalculator.calculate(list,vouchers:[v],settings:s,now:now)[0];XCTAssertEqual(discounted.discount,33600);XCTAssertEqual(discounted.total,796400);let refreshed=inputs();XCTAssertEqual(PriceCalculator.calculate(refreshed,vouchers:[v],settings:s,now:now)[0].discount,0)}
    func testManualUnitCorrectionAndExclusion(){var c=candidate(.hotel,100000,"Ambiguous amount PHP 1,000");XCTAssertNil(PriceCalculator.component(c));c.basis = .nightRoom;XCTAssertEqual(PriceCalculator.component(c)?.total,200000);c.excluded=true;XCTAssertNil(PriceCalculator.component(c))}
    func testOldSavedSettingsAndQuoteDecode()throws{let encoder=JSONEncoder();let decoder=JSONDecoder();var json=try JSONSerialization.jsonObject(with:encoder.encode(settings())) as! [String:Any];json.removeValue(forKey:"extras");let restored=try decoder.decode(SearchSettings.self,from:JSONSerialization.data(withJSONObject:json));XCTAssertEqual(restored.budget.transfers,0);XCTAssertTrue(restored.budget.paidActivity);var q=TripQuote();q.destination="NRT";json=try JSONSerialization.jsonObject(with:encoder.encode(q)) as! [String:Any];json.removeValue(forKey:"otherCosts");XCTAssertNil(try decoder.decode(TripQuote.self,from:JSONSerialization.data(withJSONObject:json)).otherCosts)}
    func testPublishedCodesRemainUnverifiedAndKeepPercentCharacter(){XCTAssertEqual(PublishedCodes.examples.count,3);XCTAssertTrue(PublishedCodes.examples.contains{$0.code=="SOLANIWAONSEN28%"});XCTAssertTrue(PublishedCodes.examples.allSatisfy{$0.terms != nil && $0.provider == .activity})}
}
